# Site settings
title: 스루의 개발로그
email: sulewoo58@gmail.com
description: "스루의 개발 블로그"
baseurl: ""
url: "http://throughkim.github.io"
facebook_username: sulewoo@naver.com
github_username:  throughkim
highlighter: pygments

# Build settings
markdown: redcarpet
permalink: pretty
