name: 스루의 개발로그
description: 
meta_description: "스루의 개발 블로그"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://throughkim.github.io'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'throughkim.github.io'
author:         'SeulWoo Kim'
